import React from "react";
import {Box, Container} from '@chakra-ui/react'
import Head from "next/head";
import NavBar from "./Navbar";
import {NavCaption} from '@/types.d'

const Layout =  ({children, pageName}:{children:React.ReactNode, pageName:NavCaption}) => {
    return (<>
        <Head>
            <title>Nida</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@500&display=swap" rel="stylesheet" />
        </Head>
        <main>
            <Box bg='teal.500' w='100%' h='16px' pos='fixed' top='0' zIndex='9999px' ></Box>
            
            <Container mt='5%' w={['95%', '80%','50%']}>
            <NavBar activePage={pageName} />
            {children}
            </Container>
        </main>
    </>
    
    );
}
export default Layout;